# Generated by Django 3.2.9 on 2022-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freePolyMath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY_FPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY', models.CharField(max_length=50)),
                ('LINK', models.CharField(max_length=300)),
                ('THEME_COLOR', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
