# Generated by Django 3.2.9 on 2022-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freePolyMath', '0002_auto_20220606_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORY_FPM',
            fields=[
                ('CATEGORY', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('LINK', models.CharField(max_length=300)),
                ('THEME_COLOR', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='category_fpm',
            name='id',
        ),
        migrations.AlterField(
            model_name='category_fpm',
            name='CATEGORY',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
