# Generated by Django 3.2.9 on 2022-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freePolyMath', '0003_auto_20220606_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISTORY_FPM',
        ),
    ]
