# Generated by Django 3.2.9 on 2022-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freePolyMath', '0004_delete_history_fpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORY_FPM',
            fields=[
                ('CATEGORY', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('LINK', models.CharField(max_length=300)),
                ('THEME_COLOR', models.CharField(max_length=50)),
            ],
        ),
    ]
